export const quotes = [
  "Cada pequeño paso que das hoy es una votación a favor de la persona que quieres ser mañana",
  "No necesitas cambiar de vida de un día para otro; necesitas mejorar un uno por ciento cada día",
  "No subas al nivel de tus metas; baja al nivel de tus sistemas y construye desde ahí",
  "El éxito no es un evento, es el resultado de hábitos que repites cuando nadie te mira",
  "Tu entorno habla más fuerte que tu fuerza de voluntad: diseña un espacio que empuje en la dirección correcta",
  "Para dejar de postergar, reduce el hábito hasta que sea tan fácil que no puedas decir que no",
  "Dos minutos son suficientes para empezar; el resto es impulso",
  "No esperes a sentir motivación: la motivación sigue a la acción, no al revés",
  "Cada día que te presentas, incluso sin ganas, estás fortaleciendo la versión de ti que quieres llegar a ser",
  "Los resultados que obtienes son una medida de los hábitos que repites, no de tus intenciones",
  "Si quieres un resultado diferente, deja de hacer lo mismo y cambia el sistema que lo produce",
  "La constancia vence a la intensidad: un hábito pequeño sostenido supera a un esfuerzo grande y aislado",
  "Hazlo obvio, hazlo atractivo, hazlo sencillo y hazlo satisfactorio",
  "No te defines por lo que haces una vez, sino por lo que haces cada día",
  "Cambia tu identidad antes de intentar cambiar tus resultados: primero sé, luego haz, después ten",
  "Un mal día no rompe tu progreso; lo que lo rompe es abandonar el sistema",
  "Diséñate para ganar: quien quiere correr por la mañana deja las zapatillas listas al lado de la cama",
  "La disciplina no es cuestión de fuerza, sino de un entorno bien diseñado",
  "Cuando el hábito es lo bastante pequeño, empezar no cuesta y continuar se vuelve natural",
  "Cada repetición es una señal que le dice a tu cerebro quién estás decidido a ser",
  "No persigas la motivación; persigue el proceso, y la motivación vendrá a encontrarte",
  "El placer inmediato de un mal hábito se paga después; el esfuerzo inmediato de un buen hábito se cobra a tu favor",
  "Lleva la cuenta de tus días en racha: ver la cadena crecer es motivo suficiente para no romperla",
  "Rodéate de personas que ya hacen lo que tú quieres hacer: el grupo normaliza la conducta que buscas",
  "Avanzar despacio está permitido; lo que no está permitido es retroceder",
  "No necesitas más tiempo; necesitas mejores decisiones repetidas cada día",
  "El objetivo no es leer un libro, es convertirte en lector; no es correr una carrera, es convertirte en corredor",
  "La versión futura de ti no es un sueño: es el resultado de los votos que emites hoy",
  "Si el hábito no se sostiene, no es que te falte voluntad, es que el sistema está mal diseñado",
  "La paciencia con los resultados y la impaciencia con las acciones son la combinación ganadora",
  "Haz que lo bueno sea fácil y lo malo sea incómodo, y tu conducta cambiará casi sola",
  "No mides tu progreso solo por cómo te ves; mídete por cuántas veces hoy elegiste la opción que la persona que quieres ser elegiría",
  "El mayor poder de un hábito no está en lo que logras, sino en en quién te conviertes mientras lo repites",
  "Empieza tan pequeño que parezca ridículo; lo ridículo que se sostiene se vuelve imparable",
  "La vida que quieres no llega cuando cambian las circunstancias; llega cuando cambian tus rutinas",
  "Hoy no tiene que ser perfecto; solo tiene que contar",
  "No te compares con quienes llevan años; compárate con quien eras ayer",
  "Un sistema bien diseñado hace que la acción correcta sea la más sencilla de elegir",
  "Cada elección, por pequeña que sea, inscribe una línea en la historia que te cuentas sobre ti mismo",
  "La mejora del uno por ciento casi no se nota hoy, pero en un año te hace casi cuarenta veces mejor",
  "Si quieres resultados duraderos, olvídate de las metas y enamórate del proceso",
  "La motivación arranca, el hábito mantiene y la identidad consolida",
  "Cuando no tengas ganas, recuerda que presentarte también es una forma de ganar",
  "El autocontrol a largo plazo no es fuerza de voluntad: es diseñar un ambiente donde no haga falta pelear",
  "Cada hábito que construyes es un peldaño hacia la persona que estás decidiendo ser",
  "No puedes cambiar lo que no haces visible; anota, mide y observa tus hábitos",
  "La fatiga de decidir se acaba cuando la buena conducta se vuelve automática",
  "Quien celebra los pequeños avances construye un cerebro ansioso por repetirlos",
  "Haz que terminar sea satisfactorio y tu cerebro querrá volver mañana",
  "La verdadera libertad no está en no tener hábitos, sino en haber elegido los correctos",
  "Tus hábitos de hoy son la profecía de tu vida de mañana",
  "El cambio verdadero no se anuncia, se practica en silencio",
  "No eres tus viejos hábitos; eres las decisiones nuevas que repites",
  "Un día no define tu identidad, pero mil días sí",
  "Si quieres un resultado extraordinario, construye una rutina ordinaria y sostenible",
  "La fuerza de voluntad se agota; el entorno no",
  "Diseña tu espacio a favor de tus metas y no tendrás que pelear contigo mismo cada día",
  "Lo que haces cuando estás cansado revela el sistema que realmente construiste",
  "Hazlo tan fácil que ni siquiera tengas que convencerte",
  "La perfección no existe; lo que existe es la racha que no rompes",
  "Cada vez que eliges el hábito correcto, le estás diciendo al universo quién estás llegando a ser",
  "No esperes las ganas: las ganas aparecen después de empezar, no antes",
  "La disciplina de hoy es la libertad de mañana",
  "Quien se enfoca en el sistema gana incluso cuando pierde un día; quien se enfoca solo en la meta sufre incluso cuando avanza",
  "Tu vida no cambia en un fin de semana; cambia en los martes a las siete de la mañana",
  "El progreso invisible construye resultados imposibles de ignorar",
  "No necesitas motivación, necesitas un hábito tan pequeño que no puedas postergarlo",
  "La clave no es hacer más, es hacer lo correcto de forma repetida",
  "Cada hábito es una semilla; no la evalúes el primer día, evalúa el bosque dentro de un año",
  "Si te cuesta empezar, es que el hábito aún es demasiado grande",
  "El entorno adecuado convierte a la persona promedio en alguien extraordinario",
  "No cambias tu vida cambiando de opinión; la cambias cambiando de rutina",
  "La acción pequeña, repetida con paciencia, supera al plan brillante que nunca ejecutas",
  "Mañana agradecerá el hábito que hoy no quisiste abandonar",
  "Ser constante es más rentable que ser intenso",
  "Tu cerebro no quiere cambiar; por eso hay que diseñarle el camino",
  "Cada vez que cedes al mal hábito, le estás enseñando a tu cerebro qué hacer la próxima vez",
  "La mejora no se siente, se acumula",
  "No se trata de cuánto haces hoy, sino de cuántos días seguidos te presentas",
  "La identidad se construye con pruebas, no con promesas",
  "Demuéstrate a ti mismo, con acciones pequeñas, que eres quien dices ser",
  "El aburrimiento de repetir es el precio del dominio",
  "Los grandes resultados llegan cuando dejas de buscar resultados y empiezas a cuidar el proceso",
  "La tentación pierde poder cuando no tienes que enfrentarte a ella cada cinco minutos",
  "Un mal hábito se combate más con diseño que con fuerza",
  "Haz lo correcto tan fácil que no hacerlo sea más incómodo que hacerlo",
  "Cada hábito que sostienes te está escribiendo por dentro",
  "El que quiere correr una maratón empieza por atarse las zapatillas",
  "No te rindas solo porque hoy no te apetece; ese es exactamente el día que cuenta",
  "Tus resultados son un reflejo tardío de tus rutinas",
  "La confianza no se piensa, se construye repitiendo",
  "Los hábitos son el interés compuesto del crecimiento personal",
  "Hoy puedes dar un paso tan pequeño que casi parezca nada; casi nada, repetido, lo es todo",
  "El proceso no es aburrido para quien se enamoró de quién se está convirtiendo",
  "No necesitas un golpe de suerte, necesitas un sistema que no dependa de la suerte",
  "El autocontrol más fuerte es el que no tienes que usar porque ya diseñaste bien el entorno",
  "Cada vez que dices 'después mañana', le estás enseñando a tu cerebro a postergar",
  "La regla de los dos minutos no es para lograr mucho hoy; es para no faltar nunca",
  "La motivación es una ola; el hábito es el mar",
  "Quien mide sus hábitos los puede mejorar; quien los ignora repite los mismos errores",
  "No se trata de ser perfecto, se trata de no romper la cadena dos veces seguidas",
  "El placer instantáneo de un mal hábito se paga con intereses; el esfuerzo de un buen hábito se cobra con intereses",
  "La versión de ti que admiras no nació un día distinta; se construyó hábito por hábito",
  "Cada vez que eliges bien, aunque sea difícil, estás creando una evidencia a tu favor",
  "No esperes a sentirte listo; empieza antes de estar listo y el hábito te dará la forma",
  "La grandeza no es un evento, es un martes ordinario donde volviste a hacer lo que prometiste",
  "Quien tiene un porqué para vivir puede soportar casi cualquier cómo, pero solo si lo repite cada día",
  "Tu vida es el promedio de tus rutinas diarias",
  "Cambia el sistema y el resultado cambiará sin que tengas que perseguirlo",
  "Lo que haces en los primeros cinco minutos después de despertar dice mucho del día que vas a tener",
  "No te avergüences de empezar muy pequeño; te avergonzarías más de no haber empezado nunca",
  "El hábito que hoy te cuesta, dentro de un año te parecerá normal y dentro de tres será parte de quién eres",
  "Cada día que te presentas estás fundando una versión más fuerte de ti mismo",
  "No confundas una caída con un fracaso; una caída solo importa si no vuelves al sistema",
  "El éxito sostenido no es emocionante; es disciplinado y silencioso",
  "Haz visible lo que quieres repetir y desaparece lo que quieres evitar",
  "La vida que sueñas está del otro lado de los hábitos que hoy te resistes a construir",
  "No necesitas más tiempo, necesitas menos fricción",
  "Quien se perdona a sí mismo rápido vuelve al hábito; quien se castiga demasiado lo abandona",
  "La repetición es la que convierte una intención en una identidad",
  "Tu entorno es la sugerencia más poderosa que recibes cada día",
  "El hábito que no se celebra no se repite",
  "Cada pequeña victoria es una prueba de que eres capaz de la siguiente",
  "La paciencia estratégica gana más batallas que la motivación explosiva",
  "No intentes convertirte en otra persona; conviértete en la mejor versión de la que ya eres, una rutina a la vez",
  "El cambio se siente lento hasta que, de repente, parece de la noche a la mañana",
  "Lo que haces cuando nadie te ve construye la vida que todos verán",
  "Un hábito debe empezar tan simple que incluso en tu peor día puedas hacerlo",
  "Los buenos hábitos son decisiones que tomaste una vez y que ya no tienes que volver a tomar",
  "No te defines por la tentación que enfrentas, sino por el sistema que diseñaste para vencerla",
  "Cada noche, el último hábito del día es una promesa para el día siguiente",
  "La clave del cambio duradero no es hacer mucho de golpe, es no dejar de hacer un poco cada día",
  "Tu futuro no es un lugar al que llegas, es un conjunto de rutinas que construyes",
  "El que se enfoca en la acción deja de necesitar ánimo; el que espera el ánimo rara vez actúa",
  "Cada hábito bueno que sostienes es una forma de respeto por la persona que quieres ser",
  "La voluntad se entrena, pero el entorno bien diseñado no requiere entrenamiento",
  "No sobreestimes un día de motivación ni subestimes un año de constancia",
  "La vida cambia cuando decides que el hábito correcto no es negociable",
  "Hazlo una vez y será un recuerdo; hazlo cien veces y será una identidad",
  "El progreso pequeño, protegido cada día, se vuelve imparable"
];

let recentQuotes = [];

export const getRandomQuote = () => {
  let availableQuotes = quotes.filter(q => !recentQuotes.includes(q));
  
  if (availableQuotes.length === 0) {
    availableQuotes = quotes;
  }
  
  const randomIndex = Math.floor(Math.random() * availableQuotes.length);
  const selectedQuote = availableQuotes[randomIndex];
  
  recentQuotes.push(selectedQuote);
  if (recentQuotes.length > 5) {
    recentQuotes.shift();
  }
  
  return selectedQuote;
};
